name: Publish Crates

on:
  workflow_call:
    secrets:
      CARGO_REGISTRY_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  crates:
    name: Publish crates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: augentic/.github/.github/actions/cargo-cache@main

      - name: Publish workspace crates
        if: startsWith(github.ref_name, 'release-')
        run: cargo publish --workspace --registry credibil
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
