name: Git identity
description: Set Git identity for the workflow.

runs:
  using: composite
  steps:
    - name: Git config
      shell: bash
      env:
        ACTOR: ${{ github.actor }}
        ACTOR_ID: ${{ github.actor_id }}
      run: |
        git config user.name "$ACTOR"
        git config user.email "${ACTOR_ID}+${ACTOR}@users.noreply.github.com"
