name: Audit

on:
  workflow_call:
    inputs:
      outdated:
        description: "List of dependencies to ignore for cargo-outdated"
        type: string
  schedule:
    - cron: '17 6 * * *'
  workflow_dispatch:
    inputs:
      outdated:
        description: "List of dependencies to ignore for cargo-outdated"
        type: string

permissions:
  contents: read

jobs:
  security_audit:
    name: Security audit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  outdated:
    name: Outdated
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-outdated

      - env:
          OUTDATED: ${{ inputs.outdated }}
        run: |
          args=(--workspace --depth 1 --exit-code 1)
          [ -n "$OUTDATED" ] && args+=(--ignore "$OUTDATED")
          cargo outdated "${args[@]}"
